# Changes here will be overwritten by Copier
_commit: v0.3.4
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage Webhooks management
distribution_name: swh-webhooks
have_cli: true
have_workers: false
package_root: swh/webhooks
project_name: swh.webhooks
python_minimal_version: '3.10'
readme_format: rst
